/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.funcionarioDAO;
import VIEW.clienteVIEW;
import DAO.sorveteDAO;
import DAO.vendaDAO;
import DTO.clienteDTO;
import DTO.funcionarioDTO;
import DTO.sorveteDTO;
import DTO.vendaDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yan henrry
 */
public class vendaVIEW extends javax.swing.JFrame {

    /**
     * Creates new form vendaVIEW
     */
    public vendaVIEW() {
        initComponents();
        listarValores();
        restaurarDadosCbxCodFun();
        restaurarDadosCbxCodCli();
        restaurarDadosCbxItem();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        cbxCodcli = new javax.swing.JComboBox<>();
        txtCodfun1 = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtData1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCarregarCampos = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVenda = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        cbxCodfun = new javax.swing.JComboBox<>();
        cbxCpf = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxItem = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnNewCliente = new javax.swing.JButton();

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        cbxCodcli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        txtCodfun1.setBackground(new java.awt.Color(255, 102, 102));

        txtCpf.setBackground(new java.awt.Color(255, 102, 102));

        txtData1.setBackground(new java.awt.Color(255, 102, 102));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("P E D I D O S");

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        btnCarregarCampos.setBackground(new java.awt.Color(255, 102, 102));
        btnCarregarCampos.setText("CARREGAR CAMPOS");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(255, 102, 102));
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 102, 102));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel4.setText("ID:");

        txtId.setBackground(new java.awt.Color(255, 102, 102));
        txtId.setEnabled(false);

        jLabel2.setText("Funcionário:");

        jLabel3.setText("Data:");

        btnCadastrar.setBackground(new java.awt.Color(255, 102, 102));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(255, 102, 102));
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tabelaVenda.setBackground(new java.awt.Color(255, 102, 102));
        tabelaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Funcionário", "Data", "Cliente", "Itens", "Quantidade" ,  "Valor da Venda"
            }
        ));
        jScrollPane1.setViewportView(tabelaVenda);

        jLabel5.setText("Cliente:");

        jLabel6.setText("Valor da Venda:    R$");

        txtValor.setBackground(new java.awt.Color(255, 102, 102));
        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        cbxCodfun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxCodfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCodfunActionPerformed(evt);
            }
        });

        cbxCpf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCpfActionPerformed(evt);
            }
        });

        txtData.setBackground(new java.awt.Color(255, 102, 102));
        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Item:");

        cbxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxItemActionPerformed(evt);
            }
        });

        jLabel8.setText("Quantidade:");

        txtQtd.setBackground(new java.awt.Color(255, 102, 102));
        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarregarCampos)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxCodfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(362, 362, 362)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxCodfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(cbxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarCampos)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNewCliente.setBackground(new java.awt.Color(255, 102, 102));
        btnNewCliente.setText("+ Novo Cliente");
        btnNewCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNewCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnNewCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
       carregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterarVenda();
        listarValores();
        Limpar();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluirVenda();
        listarValores();
        Limpar();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrarVenda();
        listarValores();
        Limpar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmprincipalVIEW objfrmprincipalVIEW = new frmprincipalVIEW();
        objfrmprincipalVIEW.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxItemActionPerformed

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdActionPerformed

    private void cbxCodfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCodfunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCodfunActionPerformed

    private void cbxCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCpfActionPerformed

    private void btnNewClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewClienteActionPerformed
        clienteVIEW cliente = new clienteVIEW();
        
        cliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNewClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendaVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNewCliente;
    private javax.swing.JComboBox<String> cbxCodcli;
    private javax.swing.JComboBox<String> cbxCodfun;
    private javax.swing.JComboBox<String> cbxCpf;
    private javax.swing.JComboBox<String> cbxItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabelaVenda;
    private javax.swing.JTextField txtCodfun1;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtData1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables


    Vector<Integer> id_funcionario = new Vector<Integer>();
    Vector<Integer> id_cliente = new Vector<Integer>();
    Vector<Integer> id_sorvete = new Vector<Integer>();
   
    Vector<funcionarioDTO> lista_funcionarios = new Vector<funcionarioDTO>();
    Vector<sorveteDTO> lista_sorvetes = new Vector<sorveteDTO>();
    Vector<clienteDTO> lista_cliente = new Vector<clienteDTO>();

    
    private void cadastrarVenda(){
        vendaDTO objvendaDTO= new vendaDTO();
        
        String data, valor_venda;
        Integer qtd, cod_fun, item, nome_cli;

        cod_fun=lista_funcionarios.get(cbxCodfun.getSelectedIndex()).getId_funcionario();
        data=txtData.getText();
        nome_cli=lista_cliente.get(cbxCodcli.getSelectedIndex()).getId_cliente();
        item=lista_sorvetes.get(cbxItem.getSelectedIndex()).getId_sorvete();
        qtd=Integer.parseInt(txtQtd.getText());
        valor_venda=txtValor.getText();
        
        
        objvendaDTO.setCod_funcionario(cod_fun);
        objvendaDTO.setData_venda(data);
        objvendaDTO.setCod_cliente(nome_cli);
        objvendaDTO.setItem_venda(item);
        objvendaDTO.setQtd_venda(qtd);
        objvendaDTO.setValor_venda(valor_venda);
        
        
        vendaDAO objvendaDAO = new vendaDAO(); 
        objvendaDAO.cadastrarVenda(objvendaDTO);
    }
    
    private void Limpar(){
        txtId.setText("");
        cbxCodfun.setSelectedIndex(0);
        txtData.setText("");
        cbxCpf.setSelectedIndex(0);
        txtValor.setText("");
        cbxItem.setSelectedIndex(0);
        txtQtd.setText("");
    }
    
   private void listarValores(){
        try {
            vendaDAO objvendaDAO = new vendaDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaVenda.getModel();
            model.setNumRows(0);
            
            ArrayList<vendaDTO> lista = objvendaDAO.pesquisarVenda();
            
            for(int num=0; num<lista.size(); num++){
                model.addRow(new Object[]{
                        lista.get(num).getId_venda(),
                        lista.get(num).getCod_funcionario(),
                        lista.get(num).getData_venda(),
                        lista.get(num).getCod_cliente(),
                        lista.get(num).getItem_venda(),
                        lista.get(num).getQtd_venda(),
                        lista.get(num).getValor_venda()
                    });
                        
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "frmVendaView Listar valores: "+erro);
        }
        
    }
   
   private void carregarCampos(){
        int setar = tabelaVenda.getSelectedRow();
        
        
        
       
        txtId.setText(tabelaVenda.getModel().getValueAt(setar, 0).toString());
        cbxCodfun.setSelectedItem(tabelaVenda.getModel().getValueAt(setar, 1));
        txtData.setText(tabelaVenda.getModel().getValueAt(setar, 2).toString());
        cbxCpf.setSelectedItem(tabelaVenda.getModel().getValueAt(setar, 3).toString());
        cbxItem.setSelectedItem(tabelaVenda.getModel().getValueAt(setar, 4).toString());
        txtQtd.setText(tabelaVenda.getModel().getValueAt(setar, 5).toString());
        txtValor.setText(tabelaVenda.getModel().getValueAt(setar, 6).toString());
        
    }
   
   private void alterarVenda(){
        int id_venda, qtd_venda, cod_fun, cod_item, nome_cli;
        String data_venda, valor_venda;
        
        id_venda=Integer.parseInt(txtId.getText());
        cod_fun=Integer.parseInt(cbxCodfun.getSelectedItem().toString());
        data_venda=txtData.getText();
        nome_cli=Integer.parseInt(cbxCodcli.getSelectedItem().toString());
        cod_item=Integer.parseInt(cbxItem.getSelectedItem().toString());
        qtd_venda=Integer.parseInt(txtQtd.getText());
        valor_venda=txtValor.getText();
        
        vendaDTO objvendaDTO = new vendaDTO();
        objvendaDTO.setId_venda(id_venda);
        objvendaDTO.setCod_funcionario(cod_fun);
        objvendaDTO.setData_venda(data_venda);
        objvendaDTO.setCod_cliente(nome_cli);
        objvendaDTO.setItem_venda(cod_item);
        objvendaDTO.setQtd_venda(qtd_venda);
        objvendaDTO.setValor_venda(valor_venda);
        
        vendaDAO objvendaDAO = new vendaDAO();
        objvendaDAO.alterarVenda(objvendaDTO);
        
    }
   
   private void excluirVenda(){
        int id_venda=Integer.parseInt(txtId.getText());
        
        vendaDTO objvendaDTO = new vendaDTO();
        objvendaDTO.setId_venda(id_venda);
        
        vendaDAO objvendaDAO = new vendaDAO();
        objvendaDAO.excluirVenda(objvendaDTO);
    }
   
   
   private void restaurarDadosCbxCodFun() {
        try {
           vendaDAO objvendaDAO = new vendaDAO();
           ResultSet rs = objvendaDAO.listarCodFun();
           
           while(rs.next()) {
               funcionarioDTO funcionario = new funcionarioDTO();
               funcionario.setId_funcionario(rs.getInt("id_funcionario"));
               funcionario.setCpf_funcionario(rs.getString("cpf_funcionario"));
               funcionario.setNome_funcionario(rs.getString("nome_funcionario"));
               
               lista_funcionarios.addElement(funcionario);
               id_funcionario.addElement(rs.getInt(1));
               cbxCodfun.addItem(funcionario.getNome_funcionario());
           }
           
        } catch(SQLException err) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar o ComboBox " + err.getMessage()); 
        }
}
   
 private void restaurarDadosCbxItem() {
        try {
           vendaDAO objvendaDAO = new vendaDAO();
           ResultSet rs = objvendaDAO.listarItem();
           
           while(rs.next()) {
               sorveteDTO sorvete = new sorveteDTO();
               
               sorvete.setId_sorvete(rs.getInt("id_sorvete"));
               sorvete.setPreco_sorvete(rs.getString("preco_sorvete"));
               sorvete.setSabor_sorvete(rs.getString("sabor_sorvete"));
               
               lista_sorvetes.addElement(sorvete);
               id_sorvete.addElement(rs.getInt(1));
               cbxItem.addItem(sorvete.getSabor_sorvete());
           }
           
        } catch(SQLException err) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar o ComboBox " + err.getMessage()); 
        }
}

   
   private void restaurarDadosCbxCodCli() {
        try {           
            vendaDAO objvendaDAO = new vendaDAO();
           ResultSet rs = objvendaDAO.listarCodCli();
           
           while(rs.next()) {
               clienteDTO cliente = new clienteDTO();
               
               cliente.setId_cliente(rs.getInt("id_cliente"));
               cliente.setCpf_cliente(rs.getString("cpf_cliente"));
               cliente.setNome_cliente(rs.getString("nome_cliente"));
               cliente.setEndereco_cliente(rs.getString("endereco_cliente"));
               cliente.setTelefone_cliente(rs.getString("telefone_cliente"));
               
               lista_cliente.addElement(cliente);
               id_cliente.addElement(rs.getInt(1));
               cbxCpf.addItem(cliente.getNome_cliente());
           }
           
        } catch(SQLException err) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar o ComboBox " + err.getMessage()); 
        }
}
   
   
    

}
